language: node_js
node_js:
   "10"
install:
  - npm install
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE mydiarydb;' -U postgres
notification:
  email: false;
script:
  - npm test
after_script:
  - npm run coverage
